
sudo: required
services:
    - docker

before_install:
    - docker build -t amraly/docker-react-starter -f Dockerfile.dev .

script:
    - docker run amraly/docker-react-starter npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react-starter"
    env: "DockerReactStarter-env"
    bucket_name: "elasticbeanstalk-eu-west-2-075664560200"
    bucket_path: "docker-react-starter"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
