
sudo: required
services:
    - docker

before_install:
    - docker build -t amraly/docker-react-starter -f Dockerfile.dev .

script:
    - docker run amraly/docker-react-starter npm run test -- --coverage
